// <auto-generated />
using System;
using CrudDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrudDemo.Data.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    [Migration("20230708061906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrudDemo.Data.Models.DepartmentEntity", b =>
                {
                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DepartmentCode");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentCode = "IT",
                            IsDeleted = false,
                            Name = "Information Technology"
                        },
                        new
                        {
                            DepartmentCode = "LOG",
                            IsDeleted = false,
                            Name = "Logistics"
                        },
                        new
                        {
                            DepartmentCode = "ENG",
                            IsDeleted = false,
                            Name = "Engineering"
                        },
                        new
                        {
                            DepartmentCode = "SUP",
                            IsDeleted = false,
                            Name = "Tech Support"
                        },
                        new
                        {
                            DepartmentCode = "RKT",
                            IsDeleted = false,
                            Name = "Rockets"
                        },
                        new
                        {
                            DepartmentCode = "BOARD",
                            IsDeleted = false,
                            Name = "Leadership"
                        });
                });

            modelBuilder.Entity("CrudDemo.Data.Models.EmployeeEntity", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentCode")
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            BirthDate = new DateOnly(1972, 3, 14),
                            DepartmentCode = "SUP",
                            Email = "",
                            FirstName = "System",
                            IsDeleted = false,
                            LastName = "System",
                            PhoneNumber = ""
                        },
                        new
                        {
                            EmployeeId = new Guid("821af220-f65e-4c4f-8e02-d83cec8fbae8"),
                            BirthDate = new DateOnly(1972, 3, 14),
                            DepartmentCode = "BOARD",
                            Email = "mars@spacey.com",
                            FirstName = "Yellon",
                            IsDeleted = false,
                            LastName = "Mask",
                            PhoneNumber = "1112223333"
                        },
                        new
                        {
                            EmployeeId = new Guid("5925ccde-f1ad-42fc-b3d8-9957f4f48794"),
                            BirthDate = new DateOnly(1972, 3, 14),
                            DepartmentCode = "BOARD",
                            Email = "bill.cool@spacey.com",
                            FirstName = "Bill",
                            IsDeleted = false,
                            LastName = "Geyts",
                            PhoneNumber = "1112223333"
                        },
                        new
                        {
                            EmployeeId = new Guid("ed91011b-0e6d-4c7c-82f5-4f39a4a3d1a8"),
                            BirthDate = new DateOnly(1980, 4, 1),
                            DepartmentCode = "ENG",
                            Email = "toinfinityandbeyond@spacey.com",
                            FirstName = "Bus",
                            IsDeleted = false,
                            LastName = "Lightyear",
                            PhoneNumber = "2223334444"
                        },
                        new
                        {
                            EmployeeId = new Guid("eb616a17-9caa-4d83-9885-bc26a92f025d"),
                            BirthDate = new DateOnly(1985, 1, 2),
                            DepartmentCode = "RKT",
                            Email = "iloverockets@spacey.com",
                            FirstName = "Robert",
                            IsDeleted = false,
                            LastName = "Goddard",
                            PhoneNumber = ""
                        },
                        new
                        {
                            EmployeeId = new Guid("fd68039f-92e7-4716-be88-522d4a14e99e"),
                            BirthDate = new DateOnly(1985, 1, 2),
                            DepartmentCode = "LOG",
                            Email = "mynamejeff@spacey.com",
                            FirstName = "Jeff",
                            IsDeleted = false,
                            LastName = "Beshoes",
                            PhoneNumber = ""
                        });
                });

            modelBuilder.Entity("CrudDemo.Data.Models.EmployeeProjectEntity", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProject");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("IsDeleted")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProjectId");

                    b.HasIndex("CreatedByEmployeeId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = new Guid("d2de792c-11c5-45d7-8e46-ca4202b077d4"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5965), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Thaicom is the name of a series of communications satellites operated from Thailand, and also the name of Thaicom Public Company Limited, which is the company that owns and operates the Thaicom satellite fleet and other telecommunication businesses in Thailand and throughout the Asia-Pacific region. The satellite projects were named Thaicom by the King of Thailand, His Majesty the King Bhumibol Adulyadej, as a symbol of the linkage between Thailand and modern communications technology.",
                            Name = "Thaicom"
                        },
                        new
                        {
                            ProjectId = new Guid("751564fe-8346-458d-98e1-067505174c70"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5968), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "In 2017, Iridium began launching Iridium NEXT, a second-generation worldwide network of telecommunications satellites, consisting of 66 active satellites, with another nine in-orbit spares and six on-ground spares. These satellites will incorporate features such as data transmission that were not emphasized in the original design. The constellation will provide L-band data speeds of up to 128 kbit/s to mobile terminals, up to 1.5 Mbit/s to Iridium Pilot marine terminals, and high-speed Ka-band service of up to 8 Mbit/s to fixed/transportable terminals. The next-generation terminals and service are expected to be commercially available by the end of 2018. However, Iridium's proposed use of its next-generation satellites has raised concerns the service will harmfully interfere with GPS devices. The satellites will incorporate a secondary payload for Aireon, a space-qualified ADS-B data receiver. This is for use by air traffic control and, via FlightAware, for use by airlines. A tertiary payload on 58 satellites is a marine AIS ship-tracker receiver, for Canadian company exactEarth Ltd. Iridium can also be used to provide a data link to other satellites in space, enabling command and control of other space assets regardless of the position of ground stations and gateways.",
                            Name = "Iridium NEXT"
                        },
                        new
                        {
                            ProjectId = new Guid("75ba4673-d95f-4e39-8b72-313dfe3fc7cf"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5971), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Commercial Resupply Services (CRS) are a series of contracts awarded by NASA from 2008–2016 for delivery of cargo and supplies to the International Space Station (ISS) on commercially operated spacecraft. The first CRS contracts were signed in 2008 and awarded $1.6 billion to SpaceX for 12 cargo transport missions and $1.9 billion to Orbital Sciences for 8 missions, covering deliveries to 2016. In 2015, NASA extended the Phase 1 contracts by ordering an additional three resupply flights from SpaceX and one from Orbital Sciences. After additional extensions late in 2015, SpaceX is currently scheduled to have a total of 20 missions and Orbital 10. SpaceX began flying resupply missions in 2012, using Dragon cargo spacecraft launched on Falcon 9 rockets from Space Launch Complex 40 at Cape Canaveral Air Force Station, Cape Canaveral, Florida. Orbital Sciences began deliveries in 2013 using Cygnus spacecraft launched on the Antares rocket from Launch Pad 0A at the Mid-Atlantic Regional Spaceport (MARS), Wallops Island, Virginia. A second phase of contracts (known as CRS2) were solicited and proposed in 2014. They were awarded in January 2016 to Orbital ATK, Sierra Nevada Corporation, and SpaceX, for cargo transport flights beginning in 2019 and expected to last through 2024.",
                            Name = "Commercial Resupply Services"
                        },
                        new
                        {
                            ProjectId = new Guid("29edb6d7-3bcc-4125-87a6-4f4f41581b7d"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5973), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "SES S.A. is a communications satellite owner and operator providing video and data connectivity worldwide to broadcasters, content and internet service providers, mobile and fixed network operators, governments and institutions, with a mission to “connect, enable, and enrich”. SES operates more than 50 geostationary orbit satellites and 16 medium Earth orbit satellites. These comprise the well-known European Astra TV satellites, the O3b data satellites and others with names including AMC, Ciel, NSS, Quetzsat, YahSat and SES.",
                            Name = "SES"
                        },
                        new
                        {
                            ProjectId = new Guid("e3dbcad9-fc36-4a7b-8aba-60b72dcbffbe"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5974), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "The JSAT constellation is a communication and broadcasting satellite constellation formerly operated by JSAT Corporation and currently by SKY Perfect JSAT Group. It has become the most important commercial constellation in Japan, and the fifth of the world. It has practically amalgamated all private satellite operators in Japan, with only B-SAT left as a local competitor.",
                            Name = "JCSAT"
                        },
                        new
                        {
                            ProjectId = new Guid("f6f4bf11-8d50-437d-bd7d-8f3bb23f1216"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5975), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Asia Satellite Telecommunications Holdings Limited known as its brand name AsiaSat is a commercial operator of communication spacecraft. AsiaSat is based in Hong Kong but incorporated in Bermuda.",
                            Name = "AsiaSat"
                        },
                        new
                        {
                            ProjectId = new Guid("69fec5a3-8afb-4eda-83d2-8948299e724f"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5976), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Orbcomm Generation 2 (OG2) second-generation satellites are intended to supplement and eventually replace the current first generation constellation. Eighteen satellites were ordered by 2008—nominally intended to be launched in three groups of six during 2010–2014—and by 2015 have all been launched, on three flights. Orbcomm has options for a further thirty OG2 spacecraft. The satellites were launched by SpaceX on the Falcon 9 launch system. Originally, they were to launch on the smaller Falcon 1e rocket.",
                            Name = "Orbcomm OG2"
                        },
                        new
                        {
                            ProjectId = new Guid("952b39a3-6376-40dc-954c-b78aa1a6a4c9"),
                            CreatedByEmployeeId = new Guid("05a50b8b-8f72-4999-a786-a3b64c830bc8"),
                            CreatedTimestamp = new DateTimeOffset(new DateTime(2023, 7, 8, 6, 19, 6, 716, DateTimeKind.Unspecified).AddTicks(5978), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "ABS, formerly Asia Broadcast Satellite, is a global satellite operator based in Hong Kong and officially incorporated in Bermuda. Its services include direct-to-home and satellite-to-cable TV distribution, cellular services, and internet services. Operating 6 communication satellites, the satellite fleet currently covers 93% of the world’s population including the Americas, Africa, Asia Pacific, Europe, the Middle East, Russia and Commonwealth of Independent States.",
                            Name = "ABS"
                        });
                });

            modelBuilder.Entity("CrudDemo.Data.Models.EmployeeEntity", b =>
                {
                    b.HasOne("CrudDemo.Data.Models.DepartmentEntity", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.EmployeeProjectEntity", b =>
                {
                    b.HasOne("CrudDemo.Data.Models.EmployeeEntity", "Employee")
                        .WithMany("Projects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrudDemo.Data.Models.ProjectEntity", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.ProjectEntity", b =>
                {
                    b.HasOne("CrudDemo.Data.Models.EmployeeEntity", "CreatedByEmployee")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CreatedByEmployee");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.DepartmentEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.EmployeeEntity", b =>
                {
                    b.Navigation("CreatedProjects");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("CrudDemo.Data.Models.ProjectEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
